backend:
  name: git-gateway
  branch: main 
media_folder: "static/images/uploads" 
public_folder: "/images/uploads" 
collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Página Inicial"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
